Agregar componente de actualizacion
its-dev-fer/nanoglow-store pull request #10
Opened 2024-08-21 22:22 UTC by DazhZs

2024-08-21 22:32 UTC, its-dev-fer requested changes
pequeño cambio de ruta

2024-08-21 22:32 UTC, its-dev-fer commented on src/routes/AppRoutes.tsx
> +        <Route path="/update" element={<UpdateForm />} />
path="/profile"

2024-08-22 21:50 UTC, DazhZs commented on src/routes/AppRoutes.tsx
> +        <Route path="/update" element={<UpdateForm />} />
Ya lo modifiqué

2024-08-23 02:55 UTC, its-dev-fer approved these changes, later dismissed

2024-08-23 15:09 UTC, its-dev-fer commented
Conflictos

2024-08-23 19:25 UTC, DazhZs commented
Conflictos arreglados

2024-08-27 01:46 UTC, its-dev-fer approved these changes

2024-08-27 01:46 UTC, merged