Creacion del login basico
its-dev-fer/nanoglow-store pull request #2
Opened 2024-08-13 03:10 UTC by MrYen2-0

Un login basico para probar

2024-08-13 14:56 UTC, its-dev-fer commented on src/components/styles/LoginForm.css
> +* {
Nota: Cuando el PR que habilita las dependencias se termine, podrás avanzar con este formulario. Fuera de eso, lo demás se ve bien.

2024-08-13 16:41 UTC, MrYen2-0 commented on src/components/styles/LoginForm.css
> +* {
Disculpe, podría proporcionarme las notas que vimos ayer de los splits por favor

2024-08-15 18:06 UTC, its-dev-fer commented on src/components/styles/LoginForm.css
> +* {
Lo encuentras en el tablero del proyecto de github

2024-08-17 04:43 UTC, its-dev-fer requested changes

2024-08-17 04:43 UTC, its-dev-fer commented on package.json
> +    "react-router-dom": "^6.26.1",
faltó ejecutar `npm version patch`

2024-08-17 04:43 UTC, its-dev-fer commented on src/App.tsx
> +      <AppRoutes />
Funciona esto? Me refiero a que si se verá el hero 3D siempre y debajo la ruta?

2024-08-17 04:43 UTC, its-dev-fer commented on src/components/Formulario-login/LoginForm.tsx
> +  };
![imagen](https://github.com/user-attachments/assets/9e94b7a3-1752-49a2-b931-132b9487d8bb)

2024-08-17 04:43 UTC, its-dev-fer commented on src/components/Formulario-login/LoginForm.tsx
> +          "Content-Type": "application/json",
Agrega el header Accept: application/json

2024-08-17 04:43 UTC, its-dev-fer commented on src/routes/AppRoutes.tsx
> +        <Route path="/" element={<LoginForm />} />
TO-DO: El path `/` mostrará un componente que use el Hero 3D, la ruta `/login` tendrá el componente `LoginForm`

2024-08-17 06:06 UTC, MrYen2-0 commented on src/App.tsx
> +      <AppRoutes />
Si funciona, cuando tenga tiempo le muestro el funcionamiento

2024-08-19 17:50 UTC, its-dev-fer commented
Como se unió formulario de registro puedes volver a corregir conflictos?

2024-08-19 18:48 UTC, MrYen2-0 commented
Espere, no lo revise. Cometi unos errores

2024-08-19 19:46 UTC, its-dev-fer approved these changes

2024-08-19 19:46 UTC, merged