add: componente Hero 3D
its-dev-fer/nanoglow-store pull request #5
Opened 2024-08-15 17:44 UTC by josep25062023

Eh  creado el componente de Hero3D ya responsivo

2024-08-15 17:56 UTC, josep25062023 commented
![Captura de pantalla 2024-08-15 115352](https://github.com/user-attachments/assets/11685c20-f915-4247-a132-85e98fc06cd1)
![Captura de pantalla 2024-08-15 115428](https://github.com/user-attachments/assets/c01b085c-4e50-42f0-bf38-e58a8d570f74)

2024-08-15 18:06 UTC, its-dev-fer requested changes

2024-08-15 18:06 UTC, its-dev-fer commented on package.json
> +    "react-tsparticles": "^2.12.2",
Se siguen usando estas dependencias?

2024-08-15 18:06 UTC, its-dev-fer commented on package.json
> +    "react-tsparticles": "^2.12.2",
Faltó ejecutar `npm version patch`

2024-08-15 18:06 UTC, its-dev-fer commented on src/App.css
> +
Si este archivo ya no tiene nada se puede eliminar

2024-08-15 18:06 UTC, its-dev-fer commented on react-particles-webgl.d.ts
> +declare module 'react-particles-webgl' {
Aún se usa este archivo?

2024-08-15 18:06 UTC, its-dev-fer commented on src/App.tsx
>  import './App.css'
Tracking.

2024-08-16 18:25 UTC, its-dev-fer approved these changes
Excelente trabajo!

2024-08-16 18:26 UTC, merged