Implementacion de las Sections en el Hero3D
its-dev-fer/nanoglow-store pull request #8
Opened 2024-08-21 03:27 UTC by EmilianoVentura7

2024-08-21 18:28 UTC, its-dev-fer commented
<img width="959" alt="imagen" src="https://github.com/user-attachments/assets/d0182030-ab0a-4261-a469-7586d5bcdfae">
Me sale ese error, puedes borrar tu carpeta node_modules y package.lock.json, después ejecutar npm i para validar si también te pasa?

2024-08-21 18:33 UTC, EmilianoVentura7 commented
si en un momento le confirmo

2024-08-21 18:43 UTC, EmilianoVentura7 commented
si tambien me pasa, ya me acorde que la primera vez que jale los cambios me paso lo mismo lo que hice fue usar estos dos comandos: 
npm install @react-three/fiber

npm i --save-dev @types/three

2024-08-21 19:01 UTC, its-dev-fer requested changes
El espaciado está bien, solo modifica la forma en la que se ven las imágenes. Falta la tarjeta blanca con sombra que va debajo

2024-08-21 19:01 UTC, its-dev-fer commented on src/components/sections/Sections.tsx
> +    <div className="flex flex-col gap-8 p-4">
Creo que el gap + el padding le agrega marcos blancos a la imagen, lo cual debe abarcar el 100% del ancho

2024-08-21 22:34 UTC, its-dev-fer commented
![imagen](https://github.com/user-attachments/assets/56f18d0b-eda3-4e9f-b690-90bb3a5b3af8)
![imagen](https://github.com/user-attachments/assets/09b28fe2-aa79-4906-a8a9-5e4ba7648e12)

Lo que puedes hacer es tener las letras más chicas en móvil y hacerlas mas grandes con md, lg y xl

2024-08-21 23:38 UTC, EmilianoVentura7 commented
Ya hice las letras más chicas en móvil

2024-08-23 02:53 UTC, its-dev-fer approved these changes

2024-08-23 02:55 UTC, merged