Implementación del Navbar
its-dev-fer/nanoglow-store pull request #9
Opened 2024-08-21 17:17 UTC by MrYen2-0

El navbar aun se tiene que corregir para que este de acuerdo al figma pero ya es algo funcional

2024-08-21 18:30 UTC, its-dev-fer requested changes

2024-08-21 18:30 UTC, its-dev-fer commented on package.json
> +    "@react-three/fiber": "^8.17.5",
Faltó ejecutar `npm version patch`

2024-08-21 18:30 UTC, its-dev-fer commented on src/components/navbar/Navbar.tsx
> +import logo from '../../assets/logo.png';
No uses el PNG, usa el formato SVG, puedes sacar los svgs de esta página: https://iconmonstr.com/

2024-08-21 18:38 UTC, MrYen2-0 commented on src/components/navbar/Navbar.tsx
> +import logo from '../../assets/logo.png';
Ok

2024-08-23 02:54 UTC, its-dev-fer submitted a review, later dismissed

2024-08-23 15:08 UTC, its-dev-fer approved these changes

2024-08-23 15:09 UTC, merged